### PR TITLE
Refactor create2

### PR DESCRIPTION
**Pull request by QGarchery**
This PRs makes so the constructor of the PreLiquidation contract does not take any argument, and instead fetches them for the sender (which is expected to be the factory). To avoid collisions, the salt is used, by simply setting it to the hash of the parameters.

The purpose is to:
- be able pre-compute the init code hash, which was very long. This allows notably to make it reasonable to compute the expected address of the pre-liquidation contract onchain;
- be more efficient gas-wise in pre-liquidation deployment, because it avoids to do a "very cold" SSTORE to set `isPreLiquidation`. Instead it uses the computation of the expected address of the pre-liquidation contract;
- being able to return an appropriate error message when the pre-liquidation contract was already deployed.

Todo:
- [ ] decide if this solution is worth it at this stage in the development
- [ ] improve gas efficiency, as it is basically unusable at the moment. See comments `Not optimized yet`:
  - make storage variables in the factory be transient variables
  - only one call to the candidate pre-liquidation contract in `isPreLiquidation`
  - only one call to the factory in the constructor of the pre-liquidation contract
- [ ] complete natspecs

### CODE REVIEW

**Comment by peyha** [comment]
Interesting !
Got some concerns though
1. This feature makes the code more complex, can you quantify how much gas this can safe during pre-liquidation deployment ? Want to make sure that this is worth it
2. Implementing transient storage either require to update the solidity version to 0.8.28 to enable the [use of the transient keyword](https://soliditylang.org/blog/2024/10/09/solidity-0.8.28-release-announcement/) either to use assembly to use TLOAD and TSTORE, potentially making the code harder to read
3. If we were to implement this, would we need to re-audit the whole project ? From a security standpoint it seems like a minor update but it still means using new opcodes so it would be best to run another round of audit

**Comment by QGarchery** [comment]
> This feature makes the code more complex, can you quantify how much gas this can safe during pre-liquidation deployment ? Want to make sure that this is worth it

Not sure but this should be less than 20k gas, the cost of a very cold SSTORE. This may not be the most important benefit of this PR though: making it possible to have deterministic addresses onchain, and being able to have a nice error message should bring the most benefit

Agree with point 2, until we get proper support in solidity.

Also agree with point 3, this is probably too late. But this was more meant as a demonstration of what we could do in the future than an actual PR we should merge right now

**Comment by MathisGD** [comment]
- note that the deployment of a preliquidation is approximately 1.4M gas anyway
- this could be achieved without this change right?
- yes

**Comment by QGarchery** [comment]
> do you have a gas cost comparison?

No, because the PR is unusable as of now (see point 2 of the todo list). I will close it, as it was more something to have in mind for the future than anything else

**Pull request closed without merging**
